### ISSUE TITLE
Download only new/missing reports ?

### ISSUE THREAD

**Issue by ITSEC-DACHSER** [joesecurity/Joe-Sandbox-Splunk-Addon#1]
Hello Joe Security-Team,

is there an option for the Splunk-Addon to download only new reports that are missing in Splunk? 

Currently we have to downloading all reports and save them again and again in our index with your API. That´s around 20GB (!!!) a day for the reports that we already have in the index. The option "Minimum Report ID" is useless to us, because you won´t increment this value by hand every time a new report was generated.

Thanks for your help!

**Comment by joesecurity** [comment]
Please make sure you have downloaded and installed the latest Joe Sandbox Splunk Addone, version 1.0.6.

**Comment by ITSEC-DACHSER** [comment]
Thanks for your quick reply. 
Yes, we are already on Version 1.0.6.
![joe_1_0_6](https://user-images.githubusercontent.com/50357205/66210990-5c1a2180-e6bb-11e9-9fef-11f5fe1c1653.PNG)

**Comment by joesecurity** [comment]
Please contact us via www.joesecurity.org/support and upload all splunk log files.

**Comment by ITSEC-DACHSER** [comment]
Ok, we will do so! Thanks.
